# Generated by Django 4.0.6 on 2022-08-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
