# Generated by Django 4.0.6 on 2022-08-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_votebox_voteoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='script',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scriptType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
