# Generated by Django 4.0.6 on 2022-08-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_script_post_scripttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='script',
        ),
        migrations.RemoveField(
            model_name='post',
            name='scriptType',
        ),
    ]
